### ISSUE TITLE
Suitability for simulating plasmonic effect in long wavelength region

### ISSUE THREAD

**Issue by MahmutRuzi** [complexphoton/MESTI.m#1]
Hello, dear author.
Thanks for sharing the code. 
Reading the paper and the documents, the method and tool seems to have the power to revolutionize photonic simulations. The capabilities are clearly listed. Is it possible to also add situation where it is not suitable for ? 
Personally, I am interested in plasmonics for sensing applications such as in SERS and SEIRA. For such simulations, most available methods such as FDTD and RCWA does not work well, either too slow or do not converge. The situation is worse for plasmonic simulations in the mid IR region (wavelength 2 micron to 20 micron). For example, to simulate the reflectance of a gold nanobar (870 nm long, 230 nm wide, 70 nm high) arrays on Si takes days using meep. 
So my question is, do the method and tool is suitable for such simulations ?

**Comment by chiaweihsu** [comment]
Hi Mahmut,

Thanks for the question! For plasmonics, you probably want to use finite-element method. MESTI uses finite difference with a fixed grid size, so it will require high spatial resolution everywhere for plasmonics, just like MEEP. The main advantage of APF/MESTI is for dealing with systems having many inputs.

Per your suggestion, we added a section describing when to (and when not to) use MESTI in the README (commit b879d3a).
